### ISSUE TITLE
[Feature Request] JSON output changes

### ISSUE THREAD

**Issue by mzrtamp** [zhycorp/node-zhycorp#103]
It looks like [this package](https://github.com/zhycorp/node-zhycorp) is cannot be used for a temporary time to scrape [bot.zhycorp.com](https://bot.zhycorp.com). Because we've migrated our database to mongo, which has changed the JSON output of the hello world page.

So, I need further help from another project maintainer @KurokuTetsuya to take care of this future, then I can release a new version.

**Comment by mzrtamp** [comment]
And of course, this has also happened to the bot list website
![image](https://user-images.githubusercontent.com/40928387/102944445-622d3580-44ed-11eb-8961-fbc19ddae58c.png)

**Comment by mzrtamp** [comment]
> And of course, this has also happened to the bot list website
> ![image](https://user-images.githubusercontent.com/40928387/102944445-622d3580-44ed-11eb-8961-fbc19ddae58c.png)

[Fixed] Done, I did this one

**Comment by satoufuyuki** [comment]
Related to #104
